application: amigos-golf
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /.*
  script: main.application
  
- url: /choose_players
  script: main.choose

libraries:
- name: webapp2
  version: latest
  
- name: jinja2
  version: latest